### ISSUE TITLE
ERRO

### ISSUE THREAD

**Issue by arthur007110** [lsoaresesilva/letscode#30]
C:\Users\arthu\letscode>ng serve
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
 91% additional asset processing scripts-webpack-plugin× ｢wdm｣: Error: ENOENT: no such file or directory, open 'C:\Users\arthu\letscode\node_modules\chart.js\dist\Chart.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Storage.provideSync (C:\Users\arthu\letscode\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:98:13)
    at CachedInputFileSystem.readFileSync (C:\Users\arthu\letscode\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:259:32)
    at Observable.rxjs_1.Observable.obs [as _subscribe] (C:\Users\arthu\letscode\node_modules\@ngtools\webpack\src\webpack-input-host.js:35:51)
    at Observable._trySubscribe (C:\Users\arthu\letscode\node_modules\rxjs\internal\Observable.js:44:25)
    at Observable.subscribe (C:\Users\arthu\letscode\node_modules\rxjs\internal\Observable.js:30:22)                        at SyncDelegateHost._doSyncCall (C:\Users\arthu\letscode\node_modules\@angular-devkit\core\src\virtual-fs\host\sync.js:22:20)
    at SyncDelegateHost.read (C:\Users\arthu\letscode\node_modules\@angular-devkit\core\src\virtual-fs\host\sync.js:49:21)
    at WebpackCompilerHost.readFileBuffer (C:\Users\arthu\letscode\node_modules\@ngtools\webpack\src\compiler_host.js:124:44)
    at VirtualFileSystemDecorator.readFile (C:\Users\arthu\letscode\node_modules\@ngtools\webpack\src\virtual_file_system_decorator.js:39:54)
    at Promise (C:\Users\arthu\letscode\node_modules\@angular-devkit\build-angular\src\angular-cli-files\plugins\scripts-webpack-plugin.js:92:49)
    at new Promise (<anonymous>)                                                                                            at scripts.map.fullPath (C:\Users\arthu\letscode\node_modules\@angular-devkit\build-angular\src\angular-cli-files\plugins\scripts-webpack-plugin.js:91:24)                                                                                      at Array.map (<anonymous>)
    at hook (C:\Users\arthu\letscode\node_modules\@angular-devkit\build-angular\src\angular-cli-files\plugins\scripts-webpack-plugin.js:90:43)

**Comment by lsoaresesilva** [comment]
Seu erro é: no such file or directory, open 'C:\Users\arthu\letscode\node_modules\chart.js\dist\Chart.js

Falta a biblioteca chartjs

Depois de clonar o projeto você deu o npm install?

**Comment by arthur007110** [comment]
dei sim, mas como tinha clonado o projeto desde quando o senhor mandou e creio que essa biblioteca não tinha sido adicionada até então resultou nesse erro, mas instalei as dependências de novo e funcionou.
